// Package hack tests the release shell scripts in this directory.
//
// They are shell rather than Go because they run in CI steps and in justfile
// recipes, but they decide what a release says, and a release that drops its
// migration notes is indistinguishable from a good one until somebody upgrades.
// So they are tested here, from Go, where `just test` already runs.
package hack

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// What git-cliff writes for an unreleased range: the header from cliff.toml,
// one version section, then its footer.
const generatedSection = `# Changelog

All notable changes to this project are documented here.

## [0.1.0] - 2026-09-05

### Features

- *(tui)* Add a live terminal dashboard (#32)

### Bug Fixes

- *(deploy)* Drop privileged and read cgroup membership from the kernel (#31)
<!-- generated by git-cliff -->
`

// The hand-written half. Shortened, but the `hogs` rename is the real one, and
// it is the note that actually went missing.
const handWritten = `# Changelog

All notable changes to this project are documented here.

## [Unreleased]

### Breaking

#### ` + "`hogs`" + ` is now ` + "`processes`" + ` on ` + "`GET /v1/events`" + `

A consumer reading ` + "`hogs`" + ` gets ` + "`undefined`" + ` rather than an error, so a
dashboard built on it goes blank without failing.
`

func write(t *testing.T, dir, name, content string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return path
}

func read(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path) // #nosec G304 - paths are test fixtures
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}

func script(t *testing.T, name string) string {
	t.Helper()
	path, err := filepath.Abs(name)
	if err != nil {
		t.Fatalf("resolve %s: %v", name, err)
	}
	return path
}

// run executes a script, keeping stderr separate so a test can assert on the
// message a maintainer would actually see.
func run(t *testing.T, name string, args ...string) (stdout, stderr string, err error) {
	t.Helper()
	cmd := exec.Command("bash", append([]string{script(t, name)}, args...)...)
	var out, errOut strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &errOut
	err = cmd.Run()
	return out.String(), errOut.String(), err
}

// mustRun runs a script that is expected to succeed.
func mustRun(t *testing.T, name string, args ...string) string {
	t.Helper()
	stdout, stderr, err := run(t, name, args...)
	if err != nil {
		t.Fatalf("%s: %v\nstderr: %s", name, err, stderr)
	}
	return stdout
}

func TestChangelogRelease(t *testing.T) {
	tests := []struct {
		name      string
		changelog string
		generated string
		version   string
		wantErr   string
		// Substrings the rewritten file must contain, in this order.
		wantOrder []string
	}{
		{
			name:      "hand-written notes sit above the generated groups",
			changelog: handWritten,
			generated: generatedSection,
			version:   "v0.1.0",
			wantOrder: []string{
				"## [Unreleased]",
				"## [0.1.0] - 2026-09-05",
				"### Breaking",
				"`hogs` is now `processes`",
				"### Features",
				"### Bug Fixes",
			},
		},
		{
			name: "an empty Unreleased section still releases",
			changelog: `# Changelog

## [Unreleased]
`,
			generated: generatedSection,
			version:   "v0.1.0",
			wantOrder: []string{"## [Unreleased]", "## [0.1.0] - 2026-09-05", "### Features"},
		},
		{
			name: "earlier releases and the git-cliff footer survive",
			changelog: handWritten + `
## [0.0.9] - 2026-08-01

### Features

- Something older
<!-- generated by git-cliff -->
`,
			generated: generatedSection,
			version:   "v0.1.0",
			wantOrder: []string{
				"## [0.1.0] - 2026-09-05",
				"### Breaking",
				"### Features",
				"## [0.0.9] - 2026-08-01",
				"- Something older",
				"<!-- generated by git-cliff -->",
			},
		},
		{
			name:      "a changelog with nothing to close is an error",
			changelog: "# Changelog\n\n## [0.0.9] - 2026-08-01\n\n- Old\n",
			generated: generatedSection,
			version:   "v0.1.0",
			wantErr:   "no [Unreleased] heading",
		},
		{
			name:      "a version that disagrees with the generated section is an error",
			changelog: handWritten,
			generated: generatedSection,
			version:   "v0.2.0",
			wantErr:   "but v0.2.0 was asked for",
		},
		{
			name:      "a generated section with no entries is an error",
			changelog: handWritten,
			generated: "# Changelog\n\n## [0.1.0] - 2026-09-05\n<!-- generated by git-cliff -->\n",
			version:   "v0.1.0",
			wantErr:   "no entries under it",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			changelog := write(t, dir, "CHANGELOG.md", tt.changelog)
			generated := write(t, dir, "generated.md", tt.generated)

			_, stderr, err := run(t, "changelog-release.sh", tt.version, generated, changelog)

			if tt.wantErr != "" {
				if err == nil {
					t.Fatalf("expected failure, got success\nstderr: %s", stderr)
				}
				if !strings.Contains(stderr, tt.wantErr) {
					t.Errorf("stderr = %q, want it to mention %q", stderr, tt.wantErr)
				}
				// A failed run must not have touched the file.
				got := read(t, changelog)
				if got != tt.changelog {
					t.Errorf("changelog was modified by a failing run")
				}
				return
			}
			if err != nil {
				t.Fatalf("changelog-release.sh: %v\nstderr: %s", err, stderr)
			}

			got := read(t, changelog)
			assertOrder(t, got, tt.wantOrder)

			if n := strings.Count(got, "## [0.1.0]"); n != 1 {
				t.Errorf("found %d headings for 0.1.0, want exactly 1\n%s", n, got)
			}
		})
	}
}

func TestReleaseNotes(t *testing.T) {
	dir := t.TempDir()
	changelog := write(t, dir, "CHANGELOG.md", handWritten)
	generated := write(t, dir, "generated.md", generatedSection)

	mustRun(t, "changelog-release.sh", "v0.1.0", generated, changelog)
	notes := mustRun(t, "release-notes.sh", "v0.1.0", changelog)

	// The regression. Before the merge fix these notes were the commit
	// subjects alone, and the rename that breaks every consumer was absent.
	assertOrder(t, notes, []string{"### Breaking", "`hogs` is now `processes`", "### Features"})

	for _, unwanted := range []string{"## [Unreleased]", "## [0.1.0]", "<!-- generated by git-cliff -->"} {
		if strings.Contains(notes, unwanted) {
			t.Errorf("notes contain %q, which belongs to the changelog and not to a release", unwanted)
		}
	}
}

func TestReleaseNotesRejectsADuplicatedVersion(t *testing.T) {
	dir := t.TempDir()
	// Exactly what `git cliff --prepend` used to produce: the generated
	// section above the hand-written one, both claiming the same version.
	doubled := `# Changelog

## [0.1.0] - 2026-09-05

### Features

- *(tui)* Add a live terminal dashboard (#32)

## [0.1.0] - 2026-09-05

### Breaking

#### ` + "`hogs`" + ` is now ` + "`processes`" + `
`
	changelog := write(t, dir, "CHANGELOG.md", doubled)

	notes, stderr, err := run(t, "release-notes.sh", "v0.1.0", changelog)
	if err == nil {
		t.Fatalf("expected failure on a duplicated version, got notes:\n%s", notes)
	}
	if !strings.Contains(stderr, "2 sections for v0.1.0") {
		t.Errorf("stderr = %q, want it to name the duplicate count", stderr)
	}
}

func TestReleaseNotesRejectsAMissingVersion(t *testing.T) {
	dir := t.TempDir()
	changelog := write(t, dir, "CHANGELOG.md", handWritten)

	_, stderr, err := run(t, "release-notes.sh", "v9.9.9", changelog)
	if err == nil {
		t.Fatal("expected failure for a version with no section")
	}
	if !strings.Contains(stderr, "no CHANGELOG.md section found") {
		t.Errorf("stderr = %q, want it to say the section is missing", stderr)
	}
}

// TestTheRealChangelogReleasesCleanly runs the scripts against the checked-in
// CHANGELOG.md. The fixtures above are small enough to be wrong in the same way
// twice; this one fails if the file people actually edit stops being releasable.
//
// It asserts the invariant rather than any particular note: everything written
// under [Unreleased] reaches the release notes. Naming the notes themselves
// would only pin whichever release was current when the test was written, and
// the version has to be one the changelog does not already carry.
func TestTheRealChangelogReleasesCleanly(t *testing.T) {
	const version = "v9.9.9"

	dir := t.TempDir()
	source, err := filepath.Abs(filepath.Join("..", "CHANGELOG.md"))
	if err != nil {
		t.Fatalf("resolve CHANGELOG.md: %v", err)
	}
	original := read(t, source)
	changelog := write(t, dir, "CHANGELOG.md", original)
	generated := write(t, dir, "generated.md",
		strings.Replace(generatedSection, "0.1.0", "9.9.9", 1))

	mustRun(t, "changelog-release.sh", version, generated, changelog)
	notes := mustRun(t, "release-notes.sh", version, changelog)

	for _, line := range unreleasedBody(original) {
		if !strings.Contains(notes, line) {
			t.Errorf("release notes dropped a hand-written line:\n  %s", line)
		}
	}

	// The generated groups have to arrive too, under the same heading.
	if !strings.Contains(notes, "### Features") {
		t.Errorf("release notes carry no generated groups\n%s", notes)
	}
}

// unreleasedBody returns the non-blank lines written under [Unreleased].
func unreleasedBody(changelog string) []string {
	var body []string
	inside := false
	for _, line := range strings.Split(changelog, "\n") {
		if strings.HasPrefix(line, "## [") {
			if inside {
				break
			}
			inside = strings.HasPrefix(line, "## [Unreleased]")
			continue
		}
		if inside && strings.TrimSpace(line) != "" {
			body = append(body, line)
		}
	}
	return body
}

func assertOrder(t *testing.T, got string, want []string) {
	t.Helper()
	at := 0
	for _, s := range want {
		i := strings.Index(got[at:], s)
		if i < 0 {
			t.Fatalf("missing %q after position %d\n%s", s, at, got)
		}
		at += i + len(s)
	}
}
