#!/usr/bin/env bash
#
# Close the [Unreleased] section of a changelog and merge git-cliff's generated
# groups into it.
#
# The two halves of a release section come from different places. Breaking
# changes and migration notes are written by hand, because no commit subject can
# say which JSON field a consumer has to rename. The per-commit lists are
# generated. Both belong under one version heading, hand-written prose first.
#
# git-cliff cannot do that on its own. `--prepend` inserts its section above
# whatever is already there, so asking a maintainer to rename [Unreleased] to
# the version first produces two headings for the same version, and
# release-notes.sh reads only the first. That shipped a release whose notes were
# commit subjects and nothing else.
#
# Usage: hack/changelog-release.sh <vX.Y.Z> <generated> [changelog]
#
#   generated   git-cliff output for the range being cut, e.g.
#               `git cliff --tag v0.1.0 --unreleased > "$gen"`
set -euo pipefail

version="${1:?usage: changelog-release.sh <vX.Y.Z> <generated> [changelog]}"
generated="${2:?usage: changelog-release.sh <vX.Y.Z> <generated> [changelog]}"
changelog="${3:-CHANGELOG.md}"

# git-cliff writes headings as "## [0.1.0] - 2026-09-05", with no leading v.
want="${version#v}"

# git-cliff emits a whole document: the header from cliff.toml, the section for
# the range, then its footer. Only the section is wanted here.
heading=$(awk '/^## \[/ { print; exit }' "$generated")
if [ -z "$heading" ]; then
  echo "$generated has no version heading, so there is nothing to release" >&2
  exit 1
fi
case "$heading" in
  *"[$want]"*) ;;
  *)
    echo "generated section is '$heading', but $version was asked for" >&2
    exit 1
    ;;
esac

body=$(awk '
  /^<!-- generated by git-cliff -->/ { exit }
  /^## \[/ { if (seen) exit; seen = 1; next }
  seen { lines[++n] = $0 }
  END {
    first = 1
    last = n
    while (first <= n && lines[first] ~ /^[[:space:]]*$/) first++
    while (last >= first && lines[last] ~ /^[[:space:]]*$/) last--
    for (i = first; i <= last; i++) print lines[i]
  }
' "$generated")

if [ -z "$body" ]; then
  echo "$generated has a heading but no entries under it" >&2
  exit 1
fi

if ! grep -q '^## \[Unreleased\]' "$changelog"; then
  echo "$changelog has no [Unreleased] heading to close" >&2
  exit 1
fi

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

HEADING="$heading" BODY="$body" awk '
  BEGIN { heading = ENVIRON["HEADING"]; body = ENVIRON["BODY"] }

  # Hand-written prose above the generated groups, which is what the changelog
  # header promises a reader. Blank lines around the seam are normalised rather
  # than preserved, so the result does not depend on how the notes were spaced.
  function flush(   i, first, last) {
    first = 1
    last = n
    while (first <= n && prose[first] ~ /^[[:space:]]*$/) first++
    while (last >= first && prose[last] ~ /^[[:space:]]*$/) last--
    for (i = first; i <= last; i++) print prose[i]
    if (last >= first) print ""
    print body
    print ""
    n = 0
  }

  # A fresh empty [Unreleased] stays at the top so the next cycle has somewhere
  # to write, and so a reader can tell the file is maintained rather than stale.
  !closed && /^## \[Unreleased\]/ {
    print "## [Unreleased]"
    print ""
    print heading
    print ""
    inside = 1
    closed = 1
    next
  }

  inside && (/^## \[/ || /^<!-- generated by git-cliff -->/) { flush(); inside = 0 }

  inside { prose[++n] = $0; next }
  { print }

  END { if (inside) flush() }
' "$changelog" > "$tmp"

# The whole point of this script is that exactly one section carries the
# version. Prove it before overwriting anything.
count=$(grep -c "^## \[${want}\]" "$tmp" || true)
if [ "$count" != "1" ]; then
  echo "expected 1 heading for $want after rewriting, found $count" >&2
  exit 1
fi

cat "$tmp" > "$changelog"
