#!/usr/bin/env bash
#
# Print the CHANGELOG.md section for one version, for use as release notes.
#
# The notes are taken from the changelog rather than generated from commit
# subjects, because a commit subject cannot say which JSON field a consumer has
# to rename. That note is hand-written above the generated sections, and a
# release that drops it is a release nobody is warned by.
#
# Usage: hack/release-notes.sh v0.1.0 [CHANGELOG.md]
set -euo pipefail

version="${1:?usage: release-notes.sh <vX.Y.Z> [changelog]}"
changelog="${2:-CHANGELOG.md}"

# git-cliff writes headings as "## [0.1.0] - 2026-09-05", with no leading v.
want="${version#v}"

# Buffering in awk rather than piping through tac: tac is GNU-only and this has
# to run on a maintainer's Mac as well as on a runner.
notes=$(awk -v want="$want" '
  # git-cliff writes this at the very end of the file, so the last section
  # would otherwise carry it into the release notes.
  /^<!-- generated by git-cliff -->/ { if (inside) exit; next }
  /^## \[/ {
    if (inside) { exit }
    if (index($0, "[" want "]") > 0) { inside = 1; next }
    next
  }
  inside { lines[++n] = $0 }
  END {
    first = 1
    last = n
    while (first <= n && lines[first] ~ /^[[:space:]]*$/) first++
    while (last >= first && lines[last] ~ /^[[:space:]]*$/) last--
    for (i = first; i <= last; i++) print lines[i]
  }
' "$changelog")

if [ -z "$notes" ]; then
  echo "no CHANGELOG.md section found for $version" >&2
  echo "a release would ship with no notes, and the breaking changes are written only there" >&2
  exit 1
fi

printf '%s\n' "$notes"
