// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type oomtracerOomEvent struct {
	_             structs.HostLayout
	TimestampNs   uint64
	MemcgId       uint64
	TaskCgroupId  uint64
	AnonRssPages  uint64
	FileRssPages  uint64
	ShmemRssPages uint64
	TotalVmPages  uint64
	LimitPages    uint64
	BadnessPoints int64
	Pid           uint32
	Tid           uint32
	Ppid          uint32
	Nspid         uint32
	OomScoreAdj   int32
	MemcgOom      uint8
	Pad           [3]uint8
	Comm          [16]int8
}

// loadOomtracer returns the embedded CollectionSpec for oomtracer.
func loadOomtracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OomtracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load oomtracer: %w", err)
	}

	return spec, err
}

// loadOomtracerObjects loads oomtracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*oomtracerObjects
//	*oomtracerPrograms
//	*oomtracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOomtracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOomtracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// oomtracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomtracerSpecs struct {
	oomtracerProgramSpecs
	oomtracerMapSpecs
	oomtracerVariableSpecs
}

// oomtracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomtracerProgramSpecs struct {
	TraceOomKillProcess *ebpf.ProgramSpec `ebpf:"trace_oom_kill_process"`
}

// oomtracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomtracerMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// oomtracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomtracerVariableSpecs struct {
	UnusedOomEvent *ebpf.VariableSpec `ebpf:"unused_oom_event"`
}

// oomtracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOomtracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomtracerObjects struct {
	oomtracerPrograms
	oomtracerMaps
	oomtracerVariables
}

func (o *oomtracerObjects) Close() error {
	return _OomtracerClose(
		&o.oomtracerPrograms,
		&o.oomtracerMaps,
	)
}

// oomtracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOomtracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomtracerMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *oomtracerMaps) Close() error {
	return _OomtracerClose(
		m.Events,
	)
}

// oomtracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOomtracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomtracerVariables struct {
	UnusedOomEvent *ebpf.Variable `ebpf:"unused_oom_event"`
}

// oomtracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOomtracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomtracerPrograms struct {
	TraceOomKillProcess *ebpf.Program `ebpf:"trace_oom_kill_process"`
}

func (p *oomtracerPrograms) Close() error {
	return _OomtracerClose(
		p.TraceOomKillProcess,
	)
}

func _OomtracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed oomtracer_x86_bpfel.o
var _OomtracerBytes []byte
