//go:build linux && (amd64 || arm64)

package bpf

import (
	"testing"
	"unsafe"
)

func TestEventSizeMatchesCompiledStruct(t *testing.T) {
	t.Parallel()

	// oomtracerOomEvent is generated by bpf2go straight from the BTF in the
	// compiled object, so it is the C struct's real size. EventSize is what the
	// decoder in internal/detector validates samples against.
	//
	// Tying them together here means a field added to oom_event without a
	// matching change on the Go side fails at build time rather than producing
	// events whose every field is shifted.
	if got := unsafe.Sizeof(oomtracerOomEvent{}); got != EventSize {
		t.Fatalf("compiled struct oom_event is %d bytes, EventSize is %d", got, EventSize)
	}
}

func TestProbeLoadsFromEmbeddedObject(t *testing.T) {
	t.Parallel()

	// Checks the committed .o is a valid BPF object with the expected program
	// and map, without needing the privileges to load it into a kernel. A
	// stale or truncated object fails here on any Linux machine, including CI
	// runners that cannot attach probes.
	spec, err := loadOomtracer()
	if err != nil {
		t.Fatalf("loadOomtracer() error = %v", err)
	}

	if _, ok := spec.Programs["trace_oom_kill_process"]; !ok {
		t.Errorf("program trace_oom_kill_process missing; have %v", spec.Programs)
	}
	if _, ok := spec.Maps["events"]; !ok {
		t.Errorf("map events missing; have %v", spec.Maps)
	}
}
